---
- name: Create or delete entities for each host
  rax_mon_entity:
      username: "{{ lookup('env', 'PUBCLOUD_USERNAME') }}"
      api_key: "{{ lookup('env', 'PUBCLOUD_API_KEY') }}"
      state: "{{ state }}"
      label: "{{ item }}"
      region: "{{ rax_region }}"
  delegate_to: localhost
  with_items: "{{ entity_labels }}"
  register: rax
  until: rax|success
  retries: 3
  delay: 5
