---
- parameter:
    name: instance_params
    parameters:
      - string:
          name: REGIONS
          default: "{REGIONS}"
          description: |
            CSV list of preferred regions, will be tried in a random order
      - string:
          name: FALLBACK_REGIONS
          default: "{FALLBACK_REGIONS}"
          description: |
            CSV list of regions that this job can run in. Any regions
            not contined in REGIONS will be used as fallbacks.
      - string:
          name: FLAVOR
          default: "{FLAVOR}"
      - string:
          name: IMAGE
          default: "{IMAGE}"
      - string:
          name: INSTANCE_NAME
          default: AUTO
          description: |
            Set instance name or "AUTO" to have it generated based on job
            name and build number. Beware the 63 char container name limit
            as container names includes the host name.
- parameter:
    name: jenkins_node_params
    parameters:
      - string:
          name: JENKINS_NODE_LABELS
          default: "{JENKINS_NODE_LABELS}"
          description: |
            Number of executors to start on each slave
      - string:
          name: JENKINS_NODE_EXECUTORS
          default: "{JENKINS_NODE_EXECUTORS}"
          description: |
            Number of executors to start on each slave
        # Bool param defaults are converted to lower case :(
        # https://review.openstack.org/#/c/473828/
      - bool:
          name: jenkins_node_exclusive
          default: "{jenkins_node_exclusive}"
          description: |
            Create slave in exclusive mode?
            An exclusive slave will only be used for jobs that specify its
            name or labels. A non exclusive node will run jobs that don't
            specify a name or label. eg common.shared_slave(){{}} blocks. Single use slaves
            should be exclusive, multi use slaves should not.
      - bool:
          name: allow_jenkins_sudo
          default: "{allow_jenkins_sudo}"
          description: |
            Grant the jenkins slave passwordless sudo. This is useful for
            single use slaves, but must not be set for long running
            slaves as it will allow jobs to pollute the build environment.


- parameter:
    name: rpc_repo_params
    parameters:
      - string:
          name: "RPC_REPO"
          default: "https://github.com/rcbops/rpc-openstack"
      - string:
          name: "RPC_BRANCH"
          default: "{RPC_BRANCH}"

- parameter:
    name: rpc_eng_ops_params
    parameters:
      - string:
          name: "RPC_ENG_OPS_REPO"
          default: "git@github.com:rcbops/rpc-eng-ops"
      - string:
          name: "RPC_ENG_OPS_BRANCH"
          default: "{RPC_ENG_OPS_BRANCH}"

- parameter:
    name: rpc_deploy_params
    parameters:
      - string:
          name: "DEPLOY_SWIFT"
          default: "{DEPLOY_SWIFT}"
          description: "Deploy Swift? yes/no"
      - string:
          name: "DEPLOY_CEPH"
          default: "{DEPLOY_CEPH}"
          description: "Deploy Ceph? yes/no"
      - string:
          name: "DEPLOY_ELK"
          default: "{DEPLOY_ELK}"
          description: "Deploy ELK? yes/no"
      - string:
          name: "DEPLOY_MAAS"
          default: "{DEPLOY_MAAS}"
          description: "Deploy and verify maas? yes/no"
      - string:
          name: "DEPLOY_IRONIC"
          default: "{DEPLOY_IRONIC}"
          description: "Deploy Ironic? yes/no"
      - text:
          name: "USER_VARS"
          default: "{USER_VARS}"
          description: "OSA/RPC USER_VARS to inject for this build"
      - string:
          name: "UPGRADE_FROM_REF"
          default: "{UPGRADE_FROM_REF}"
          description: "An tag/sha/ref to upgrade from"

- parameter:
    name: rpc_gating_params
    parameters:
      - string:
          name: RPC_GATING_BRANCH
          default: "master"
          description: |
            Version of rpc-gating. This is used when loading the rpc-gating
            groovy library, and when cloning RPC_GATING_REPO into each
            workspace. The clone source is always rcbops/rpc-gating.

- parameter:
    name: kibana_selenium_params
    parameters:
      - string:
          name: "KIBANA_SELENIUM_REPO"
          default: "https://github.com/rcbops-qe/kibana-selenium.git"
      - string:
          name: "KIBANA_SELENIUM_BRANCH"
          default: "{KIBANA_SELENIUM_BRANCH}"

- parameter:
    name: rpc_maas_params
    parameters:
      - string:
          name: "RPC_MAAS_REPO"
          default: "https://github.com/rcbops/rpc-maas"
      - string:
          name: "RPC_MAAS_BRANCH"
          default: "{RPC_MAAS_BRANCH}"

- parameter:
    name: tigkstack_params
    parameters:
      - string:
          name: "DEPLOY_TELEGRAF"
          default: "{DEPLOY_TELEGRAF}"
      - string:
          name: "DEPLOY_INFLUX"
          default: "{DEPLOY_INFLUX}"

- parameter:
    name: standard_job_params
    parameters:
      - string:
          name: "SLAVE_TYPE"
          default: "{SLAVE_TYPE}"
          description: >
            Standard jobs can be run on different types of slave. The default
            for this parameter is set to "instance" for a compute instances. To
            use a Docker container set this parameter to "container".
