---
- hosts: localhost
  user: root
  vars_files:
    - vars/all.yml
  tasks:
    - name: Write default overrides
      copy:
        content: "{{ default_gating_overrides|to_nice_yaml }}"
        dest: "{{ gating_overrides_file }}"

    - name: Write environment specific overrides
      lineinfile:
        dest: "{{ gating_overrides_file }}"
        line:  "{{ gating_overrides|to_nice_yaml }}"

    - name: Append USER_VARS
      lineinfile:
        dest: "{{ gating_overrides_file }}"
        line: "{{ lookup('env', 'USER_VARS') }}"
