---
- hosts: localhost
  user: root
  vars_files:
    - vars/all.yml
  tasks:
    - name: write overrides
      copy:
        content: "{{ gating_overrides|to_nice_yaml }}"
        dest: "{{ gating_overrides_file }}"

    - name: append USER_VARS
      lineinfile:
        dest: "{{ gating_overrides_file }}"
        line: "{{ lookup('env', 'USER_VARS') }}"
