- hosts: "{{ target_hosts }}"
  tasks:
    - name: Create temporary directory to store artifacts
      file:
        path: "{{ artifacts_dir }}"
        state: directory
      delegate_to: "localhost"
      run_once: yes

    - name: Grab host data
      command: >
               rsync
               --archive
               --compress
               --verbose
               --relative
               --rsh 'ssh -o StrictHostKeyChecking=no'
               --ignore-missing-args
               {{ inventory_hostname }}:{{ item }}
               {{ artifacts_dir }}/{{ ansible_hostname }}
      with_items:
        - "/openstack/log"
        - "/etc"
        - "/var/log"
      delegate_to: "localhost"
      tags:
        - skip_ansible_lint

    - name: List containers
      command: "lxc-ls -1"
      failed_when:
        - "{{ containers.rc != 0 }}"
        - "{{ containers.msg != '[Errno 2] No such file or directory' }}"
      changed_when: false
      register: containers

    - name: Grab container data
      command: >
               rsync
               --archive
               --compress
               --verbose
               --relative
               --rsh 'ssh -o StrictHostKeyChecking=no'
               --ignore-missing-args
               {{ inventory_hostname }}:{{ item[1].pre }}/{{ item[0] }}{{ item[1].post }}
               {{ artifacts_dir }}/{{ ansible_hostname }}
      when: "{{ containers.rc == 0 }}"
      with_nested:
        - "{{ containers.stdout_lines | default([]) }}"
        -
          - { pre: "/var/lib/lxc", post: "/rootfs/etc" }
          - { pre: "/var/lib/lxc", post: "/delta0/etc" }
      delegate_to: "localhost"
      tags:
        - skip_ansible_lint
  vars:
    workspace: "{{ lookup('env', 'WORKSPACE') }}"
    artifacts_dir: "{{ workspace }}/artifacts"
    target_hosts: "localhost"
