---
- hosts: job_nodes
  connection: local
  gather_facts: False
  tasks:
    - name: List host entities
      command: "raxmon-entities-list"
      failed_when: "{{ list_entities.stdout | regex_search('Total: [0-9]+$') == None }}"
      delegate_to: localhost
      register: list_entities
      until: list_entities|success
      retries: 3
      delay: 5

    - name: Delete host entities
      command: "raxmon-entities-delete --id {{ list_entities.stdout | regex_search('id=en[a-zA-Z0-9]+ label=' + item + ' ') | regex_search('en[a-zA-Z0-9]+') | quote }}"
      with_items: "{{ entity_labels }}"
      register: delete_entities
      until: delete_entities|success
      retries: 3
      delay: 5
