---
- name: Secure Webhook Proxy Node
  hosts: job_nodes
  user: root
  vars:
    ip_address_whitelist: "{{ lookup('env', 'SSH_IP_ADDRESS_WHITELIST') }}"
  pre_tasks:
    - name: Install apt packages
      apt:
        pkg: "ufw"
        state: installed
        update_cache: yes

    - name: Reset UFW
      ufw:
        state: reset

    - name: Allow ssh
      ufw:
        rule: allow
        port: 22
        src: "{{ item }}"
      with_items: "{{ ip_address_whitelist }}"

    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny

    - name: Add RPC public keys to authorized_keys
      authorized_key:
        user: "root"
        key: "{{ lookup('file', lookup('env', 'WORKSPACE')+'/rpc-gating/keys/rcb.keys') }}"
        state: "present"
  roles:
    - role: willshersystems.sshd
      sshd:
        ListenAddress:
          - "0.0.0.0"
        PasswordAuthentication: "no"
        X11Forwarding: "no"
        PrintLastLog: "no"
        GatewayPorts: "no"
        ClientAliveInterval: 15
        Compression: "yes"
    - role: jnv.unattended-upgrades

- name: Configure Webhook Proxy Node
  hosts: job_nodes
  user: root
  vars:
    github_cidr: "192.30.252.0/22"
  pre_tasks:
    - name: Install apt packages
      apt:
        pkg: "apache2-utils"
        state: installed
        update_cache: yes

    # The nginx instance for basic auth listens on 80
    # the ssh tunnels listens on 8888 but is not open to the public.
    - name: Allow webhooks
      ufw:
        rule: allow
        port: 80
        src: "{{github_cidr}}"

    - name: Write ip file
      delegate_to: localhost
      copy:
        dest: "{{WORKSPACE}}/instance_address"
        content: "{{ansible_default_ipv4.address}}"

    - name: "create htpasswd file"
      shell: |
        cd ~jenkins
        htpasswd -cb .htpasswd {{webhookproxy_user}} {{webhookproxy_pass}}
  roles:
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_vhosts:
        - listen: 80
          server_name: "webhookproxy"
          root: "/dev/null"
          extra_parameters: |
            location ~ /(ghprb|github-webhook) {
              auth_basic "RPC Github Webhooks";
              auth_basic_user_file /var/lib/jenkins/.htpasswd;
              proxy_bind 127.0.0.1;
              proxy_pass https://localhost:8888;
              # Don't pass auth header on to jenkins.
              proxy_set_header Authorization "";
            }
